### ISSUE TITLE
Export and import of definitions

### ISSUE THREAD

**Issue by fenollp** [michaelklishin/rabbit-hole#138]
The call
```
curl 'http://svr:15672/api/definitions?download=defs.json'
```
gives something akin to:
```yaml
rabbit_version: 3.7.16
users:
- name: somename
  password_hash: blipblop
  hashing_algorithm: rabbit_password_hashing_sha256
  tags: administrator
vhosts:
- name: "/"
permissions:
- user: somename
  vhost: "/"
  configure: ".*"
  write: ".*"
  read: ".*"
topic_permissions: []
parameters: []
global_parameters:
- name: cluster_name
  value: rabbit@304334d98560
policies: []
queues:
- name: some.q.thing
  vhost: "/"
  durable: false
  auto_delete: true
  arguments:
    x-message-ttl: 2000
- name: another.queue
  vhost: "/"
  durable: false
  auto_delete: true
  arguments: {}
exchanges:
- name: myx
  vhost: "/"
  type: topic
  durable: false
  auto_delete: false
  internal: false
  arguments: {}
bindings:
- source: myx
  vhost: "/"
  destination: some.q.thing
  destination_type: queue
  routing_key: v1.myapp.*
  arguments: {}
- source: myx
  vhost: "/"
  destination: another.queue
  destination_type: queue
  routing_key: v1.myapp.blip.blop
  arguments: {}
```

There's a great amount of chance we will be needing this (unimplemented) call.

Do you have any
* plans on this
* work started on this
* ideas on how it should be done
* pointers to where in the code I could start from
?

Thanks :)
